web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  links:
    - mysql
    - smtp
mysql:
  image: mysql:5.6.23
  ports:
    - "3307:3306"
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-mg-latest
  ports:
    - "1095:1080"
