web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  ports:
    - "8095:80"
  links:
    - mysql
  env_file:
    - env
mysql:
  image: mysql:5.6.23
  env_file:
    - env
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-mg-latest
  ports:
    - "1095:1080"
