web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - ./bin/conf/stage/env_stage
mysql:
  image: mysql:5.6.23
  ports:
    - "3307:3306"
  env_file:
     - ./bin/conf/stage/env_stage
