web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  ports:
    - "8095:80"
  env_file:
    - ./bin/conf/stage/env_stage
mysql:
  image: mysql:5.6.23
  env_file:
     - ./bin/conf/stage/env_stage
